import type { Metadata } from "next";
import { PrimeReactProvider } from "primereact/api";
import Providers from "@components/Providers";

import { Geist, Geist_Mono } from "next/font/google";
//import "primereact/resources/primereact.css";
import "primereact/resources/themes/tailwind-light/theme.css";

import "primeflex/primeflex.css";
import "primeicons/primeicons.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PrimeReactProvider>
      <Providers>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </body>
        </html>
      </Providers>
    </PrimeReactProvider>
  );
}
